"""Rebuild the five static pages; Python standard library only."""
from pathlib import Path
from html import escape
ROOT = Path(__file__).resolve().parent
PAGES = [
('index','Overview','Designing ranking systems','Four surfaces. Four different decisions.'),
('video','01 · Video','Recommend the next video','Optimize the viewing session, then design the slate.'),
('comments','02 · Comments','Rank a conversation','Preserve the tree. Keep expensive work away from reads.'),
('ads','03 · Ads','Rank ads by expected value','Get the probability, the bid unit, and the eligibility rules right.'),
('search','04 · Search','Personalize marketplace search','Respect explicit intent before inferring a preference.')]
CONTENT = {}
CONTENT['index'] = '''
<p class="lead">A ranking system is a sequence of decisions about what becomes visible. The right architecture depends on the shape of those decisions: a video slate, a branch of replies, an ad slot, or a page of available listings.</p>
<div class="note"><p><strong>How to read this collection.</strong> Start with the comparison below, then read any case independently. The scenarios and numerical examples are teaching assumptions, not reports of any company’s current production architecture. Model names are options to evaluate, not required components.</p></div>
<h2 id="contract">Start with the decision contract</h2>
<p>Before drawing services, write one sentence: given these inputs, return this output, within this deadline, subject to these constraints. That sentence prevents a familiar failure: building an impressive recommender for the wrong product surface.</p>
<p>Separate four objects. The <strong>product objective</strong> describes the user outcome. The <strong>training target</strong> is an observable proxy. The <strong>serving score</strong> combines predictions and constraints. The <strong>experiment metric</strong> decides whether the change helped. They may be related without being interchangeable. A click label, for example, does not directly measure a satisfying viewing session.</p>
<div class="table-wrap comparison" tabindex="0" role="region" aria-label="Compare four ranking surfaces"><table><thead><tr><th>Surface</th><th>Candidate boundary</th><th>Decision</th><th>Characteristic failure</th></tr></thead><tbody>
<tr><td><a href="video.html">Next video</a></td><td>Large, open catalog</td><td>A diverse slate conditioned on the current session</td><td>Clickbait and repetitive recommendations</td></tr>
<tr><td><a href="comments.html">Comments</a></td><td>Children of one parent in one thread</td><td>An ordered sibling list</td><td>Flattened conversations and hot-thread contention</td></tr>
<tr><td><a href="ads.html">Advertising</a></td><td>Eligible campaigns under current policy and budget constraints</td><td>Value estimates passed to allocation and pricing</td><td>Wrong bid units, stale eligibility, immature labels</td></tr>
<tr><td><a href="search.html">Marketplace search</a></td><td>Listings satisfying explicit query constraints</td><td>Results suited to this trip and user</td><td>Personalization overriding dates, price, or location</td></tr>
</tbody></table></div>
<h2 id="paths">Draw three paths, then connect them</h2>
<div class="pipeline" role="img" aria-label="Serving reads current features; feedback updates features; training publishes versioned models"><div><b>01 / SERVING</b>Request → candidates → scores → final output<span>Deadline, fallback, eligibility</span></div><div><b>02 / FEEDBACK</b>Events → deduplication → fresh aggregates<span>Event time, late arrivals, privacy</span></div><div><b>03 / TRAINING</b>Historical snapshots → labels → model → rollout<span>Leakage, evaluation, compatibility</span></div></div>
<p>The paths meet at a versioned contract: feature definitions, model inputs, index embeddings, policy rules, and event schemas must agree. Record what the server knew when it made a decision. Reconstructing an old impression with today’s availability or tomorrow’s engagement creates leakage, even if the training code is otherwise correct.</p>
<p>For every stage, name an owner, an input/output budget, and a fallback. A fallback must still obey hard constraints. A cached ad can be ineligible; a popular listing can be unavailable. Reliability is returning a valid degraded answer, not merely returning something.</p>
<h2 id="budget">Explore the candidate-cost trade-off</h2>
<p>Retrieval determines which items the ranker can ever select. Increasing that set may improve coverage but increases downstream cost. This calculator uses a deliberately simple linear cost model; it does not estimate retrieval recall or hardware performance.</p>
<div class="lab" id="budget-lab"><h3>Candidate budget</h3><label>Candidates scored <output id="candidate-value">1000</output><input aria-label="Candidates scored" id="candidates" type="range" min="100" max="5000" step="100" value="1000"></label><label>Ranker cost per candidate (milliseconds)<input id="cost" type="number" min="0.001" max="1" step="0.005" value="0.04"></label><output id="budget-result" aria-live="polite"></output><p>Assumptions: 80 ms other work + 10 ms ranker setup; 200 ms end-to-end target. Actual batching, queueing, network fan-out, and tail behavior must be measured together.</p></div>
<h2 id="evidence">Make evaluation answer the right question</h2>
<p>Use candidate coverage to assess retrieval, judged ordering or mature outcomes to assess ranking, and guardrails to assess the whole experience. A model improvement measured after candidate generation says nothing about relevant items excluded upstream. Report segment results for sparse-history users, new items, languages, and traffic regimes.</p>
<p>Historical exposure selects what gets labels. Logging position is useful context; it is not proof of unbiased learning. Distinguish the probability of selecting an item from the probability of a user examining its position. A correction needs an explicit observation model and assumptions about overlap and confounding. Small randomized interventions can help estimate those quantities, but they must be designed and logged accordingly. <a href="https://arxiv.org/abs/1608.04468">Joachims et al.</a> provides a formal learning-to-rank treatment.</p>
<p>Ramp with a rollback plan and compare user-level outcomes with an experiment appropriate to the unit of interference. Changes to a ranked slate can affect later actions; impressions from the same user are not automatically independent samples.</p>
<div class="exercise"><h3>Design exercise</h3><p>A new model improves ranking NDCG but reduces completion for first-time users. What do you inspect before changing the loss?</p><details><summary>Reason it through</summary><p>Check candidate coverage for new users, availability of session features, score distributions, label maturity, and whether the evaluation population matches first-time traffic. Inspect the final slate and fallback rate. Only then ask whether the target or model is responsible.</p></details></div>
<h2 id="sources">Provenance and further reading</h2>
<p class="sources">These are original teaching scenarios and diagrams developed from personal study notes. The four problem prompts were inspired by <a href="https://www.hack2hire.com/question-bank/companies/reddit/ml-system-design">Hack2Hire’s ML system-design collection</a>; its solutions and diagrams are not reproduced here. Each chapter links research or official documentation supporting specific mechanisms. The companion <a href="../search-ml/index.html">Search &amp; ML Study Notes</a> develops retrieval mathematics and on-device designs in more detail.</p>
'''
CONTENT['video'] = '''
<p class="lead">The next-video rail is a small slate with a large downstream effect. Choosing its first item also chooses the likely autoplay transition, so a strong per-item click predictor can still create a poor session.</p>
<h2 id="contract">1. Define the output and the objective</h2>
<p>Assume the product needs five suggestions beside the current video and one autoplay choice. The request includes the current item, coarse language preferences, permitted history, and recent session actions. The desired outcome is a satisfying continuation, with guardrails for unwanted repetition and negative feedback.</p>
<p>Use click, meaningful consumption, explicit satisfaction signals, and dismissals as separate measurements before combining them. A thirty-second watch has different meaning on a forty-second clip and a two-hour lecture. Normalization, clipping, and missing-label rules are product choices that should be documented and evaluated. Never label every unshown video a rejected recommendation.</p>
<div class="note"><p><strong>Scenario assumptions:</strong> a large video catalog, a five-item slate, and a 250 ms end-to-end target. The example narrows to 1,000 candidates, scores them, then assembles five. These are design inputs to test, not universal operating points.</p></div>
<h2 id="architecture">2. Separate coverage, scoring, and slate assembly</h2>
<div class="pipeline" role="img" aria-label="Video pipeline: retrieve candidates, rank items, assemble a safe diverse slate"><div><b>RETRIEVE</b>Session vector + current-video neighbors + fresh pool<span>Union, eligibility, deduplication</span></div><div><b>RANK</b>Predict several engagement outcomes<span>Richer user–item interactions</span></div><div><b>ASSEMBLE</b>Policy checks + redundancy penalty<span>Five suggestions and autoplay</span></div></div>
<p>Begin with a related-item and popularity baseline so the system has a usable path without a personalized model. A learned retrieval model can later map the user/session and videos into compatible vector spaces. Precomputed item vectors make approximate nearest-neighbor search possible; expensive pair-specific features belong in the ranker. The published <a href="https://research.google/pubs/deep-neural-networks-for-youtube-recommendations/">YouTube recommendation paper</a> is a foundational example of separating candidate generation from ranking, rather than a specification for this scenario.</p>
<p>Combine sources deliberately. If the fresh-content pool is always truncated before ranking, it contributes no cold-start coverage. Track source contribution through every stage. Deduplicate by stable item ID, then inspect near-duplicates at slate assembly.</p>
<p>A tree model with engineered pair features is a useful ranking baseline. A neural interaction model becomes attractive when learned embeddings or sequence context add measurable value. <a href="https://research.google/pubs/wide-deep-learning-for-recommender-systems/">Wide &amp; Deep</a> is one approach to combining sparse feature interactions with learned representations. Choose using quality, serving cost, training complexity, and maintainability on the actual workload.</p>
<h2 id="freshness">3. Give each signal an honest freshness contract</h2>
<p>Long-term interests can be computed in batch. Recent watched items need a faster update path. An explicit “not interested” action should take effect promptly, including when the learned model is unavailable. Put such controls in a serving-readable suppression store rather than waiting for the next training run.</p>
<p>Use event IDs to deduplicate feedback, event timestamps to define windows, and an explicit policy for late events. Historical features must reflect what was available at the decision time, not just the eventual event time. Late-arriving events can otherwise make offline replay look better than live serving.</p>
<p>Deploy retrieval weights and item-index versions as a compatible pair. Changing one tower can change the geometry of the space; mixing old item vectors with a new query tower needs validation. Keep a rollback pair available, and measure fresh-item reachability separately from average recall.</p>
<h2 id="slate">4. Optimize the slate without hiding the trade-off</h2>
<p>Suppose the top four videos are nearly identical clips from one channel. The ranking scores may be correct individually, while the slate wastes positions. A greedy redundancy penalty can make that trade-off explicit:</p>
<div class="formula">next = argmax over eligible unselected items i:
  λ · relevance(i) − (1 − λ) · max similarity(i, selected)</div>
<p>Use comparable score scales, define the empty-slate case, and recompute the similarity term after each selection. This MMR-style heuristic is not a guarantee of satisfaction or fairness. Hard restrictions, such as user blocks, should be enforced independently. Reserve exploration through a separately defined stochastic policy and log its actual selection probabilities; a diversity penalty alone does not create randomized exploration.</p>
<h2 id="evaluation">5. Check what improved, and who paid for it</h2>
<p>Measure candidate coverage, ordering quality on an appropriate judged or mature-label set, and slate-level redundancy. Online, look at satisfaction signals and negative feedback alongside consumption. Track new-item and small-creator exposure without assuming equal exposure is always the correct objective.</p>
<p>A timeout budget includes feature fetches, retrieval, scoring, slate assembly, and headroom. Stage p99 values do not simply add into a measured end-to-end p99. Record the actual request trace and load-test queueing. For a partial retrieval failure, score the remaining eligible pool; if the whole personalized path fails, use a current, policy-checked related-content fallback.</p>
<div class="exercise"><h3>Trace the failure</h3><p>Fresh videos enter the index within two minutes but receive almost no impressions. Where might they disappear?</p><details><summary>Suggested investigation</summary><p>Inspect retrieval-source quotas, score compatibility across pools, truncation before ranking, missing-feature defaults, and final slate rules. An ingest freshness metric can be healthy even when fresh-item exposure is zero. Add per-stage candidate survival metrics before increasing exploration traffic.</p></details></div>
<h2 id="checklist">6. A reviewable design</h2>
<ul><li>One documented label specification, including observation windows and missing outcomes.</li><li>Candidate-source survival metrics and a quality-versus-cost curve.</li><li>Versioned retrieval/index compatibility and a fallback that respects user controls.</li><li>Separate ownership of item scoring, slate restrictions, and exploration policy.</li><li>A rollout gate with user outcomes, latency, fallback rate, and important segment results.</li></ul>
'''
CONTENT['comments'] = '''
<p class="lead">A discussion is a tree, not a bag of candidate items. Ranking its sibling lists independently gives readers an intelligible conversation and gives the system a bounded place to apply each update.</p>
<h2 id="contract">1. Keep the parent–child boundary</h2>
<p>Assume comments are shown beneath a post, with replies nested under their parents. Each parent has a paginated ordered list of direct children. A “best” mode can use a quality score; “new” can use time; a moderation policy determines what is visible at all.</p>
<p>The storage key is conceptually <code>(post_id, parent_id, sort_mode, ranking_version)</code>. A comment can be ranked among its siblings without being compared with every comment elsewhere on the site. A reply to a weak parent may remain hard to discover, so sibling ranking alone does not solve navigation or summarization of a long discussion.</p>
<h2 id="paths">2. Make updates asynchronous and reads predictable</h2>
<div class="pipeline" role="img" aria-label="Comment ranking: events update sibling order, readers request precomputed pages"><div><b>UPDATE</b>Vote / edit / moderation event<span>Deduplicate → update features → score</span></div><div><b>MATERIALIZE</b>Ordered siblings for each mode<span>Version + cursor contract</span></div><div><b>READ</b>Fetch page + comment bodies<span>Apply current visibility rules</span></div></div>
<p>Start with a deterministic score that can be explained and recomputed. Materialize the ordering when votes or other relevant signals change. A cache miss can reconstruct a bounded page or use a simpler order; it should not launch unconstrained model inference over a viral thread.</p>
<p>For a sorted-set implementation, a score update is <code>O(log K)</code> for a sibling list with K entries. That is the data-structure operation, not the cost of the whole event pipeline. Feature retrieval, scoring, replication, and any ancestor propagation add work. Redis documents <a href="https://redis.io/docs/latest/commands/zadd/">ZADD</a> and <a href="https://redis.io/docs/latest/commands/zrange/">range retrieval</a> separately.</p>
<p>A hot parent can still receive more writes than one key or worker can handle. Coalesce multiple vote changes, use idempotent updates, and bound re-ranking work. If the score depends on descendant activity, explicitly decide whether and how updates propagate to ancestors; the “only one list changes” simplification no longer holds.</p>
<h2 id="confidence">3. Separate vote confidence from relevance</h2>
<p>A comment with one positive vote has 100% approval, but very little evidence. The Wilson lower bound provides a conservative summary of a binomial proportion. It can be a teaching baseline for vote confidence; it is not a model of whether the comment answers the parent.</p>
<div class="formula">n = up + down; p = up / n
lower = [p + z²/(2n) − z·√(p(1−p)/n + z²/(4n²))]
        / [1 + z²/n]</div>
<p>For this baseline, define zero votes as score zero and use z = 1.96. The confidence interpretation assumes a suitable binomial sampling model. Real voters are selected by exposure, may coordinate, and are not independent draws; the number is a ranking heuristic under those violations. It does not correct visibility bias.</p>
<div class="lab" id="vote-lab"><h3>Confidence versus raw approval</h3><label>Positive votes<input type="number" id="upvotes" min="0" max="100000" step="1" value="1"></label><label>Negative votes<input type="number" id="downvotes" min="0" max="100000" step="1" value="0"></label><output id="vote-result" aria-live="polite"></output><p>Compare 1 positive / 0 negative with 90 positive / 10 negative. Confidence can reverse their order despite a lower observed approval rate.</p></div>
<h2 id="learned">4. Add learned signals at an explicit seam</h2>
<p>A learned relevance model can use parent context, comment text, and permitted author or thread features. Evaluate it against clear judgments: helpfulness, topicality, civility, or another specified objective. Those are different tasks, and community norms can change their labels.</p>
<p>If blending a model with a vote-confidence score, normalize and validate their scales. An arbitrary weighted sum is not automatically interpretable. Version the blend, record component scores, and retain a deterministic fallback. Refresh text features after edits; assuming comments never change makes stale embeddings a correctness bug.</p>
<p>Moderation overrides are separate from relevance. Recheck current access and removal state on reads, even if a cached ordering still contains the ID. Define whether removing a parent hides its whole subtree or leaves a placeholder that preserves permitted replies.</p>
<h2 id="pagination">5. Pagination is part of ranking correctness</h2>
<p>If votes reorder the list between pages, an offset can skip or repeat comments. A cursor based on score and ID is stable only relative to a defined ordering version. Options include a short-lived snapshot, an ordering epoch, or accepting eventual changes while deduplicating IDs in the client. State the consistency promise.</p>
<p>Use a deterministic tie-breaker. Preserve parent IDs when fetching bodies, and avoid attaching a reply to the wrong branch after deletion. When old and new ranking versions coexist, partition caches by version so a cursor cannot silently cross between them.</p>
<h2 id="evaluation">6. Evaluate conversations, not just votes</h2>
<p>Check judged helpfulness within sibling lists, moderation leakage, order staleness, read latency, and the exposure of new comments. More replies can indicate a useful discussion or an argument; it is an ambiguous success metric. Run experiments at a unit that acknowledges shared thread exposure, and inspect user segments rather than treating every vote as an independent observation.</p>
<div class="exercise"><h3>Change the assumptions</h3><p>You decide a parent’s score should depend on the quality of its descendants. What changes in the update design?</p><details><summary>Suggested answer</summary><p>An event may now affect ancestors. Introduce bounded propagation or periodic subtree aggregation, coalesce hot-thread updates, and measure lag. Keep the cheap sibling-list operation, but stop describing total processing as a single O(log K) update.</p></details></div>
'''
CONTENT['ads'] = '''
<p class="lead">An ad score represents an estimate with economic units. Before choosing a model, identify what event the advertiser pays for and which constraints make a candidate eligible.</p>
<h2 id="contract">1. Name the event and the bid unit</h2>
<p>Assume the service receives an allocated ad slot, user context, and eligible campaign candidates. It produces value estimates for an allocation service. Targeting, remaining budget, frequency caps, creative policy, and pacing decisions must be reflected in eligibility. Allocation and payment rules are a separate specified contract.</p>
<p>Do not assume every ad auction is second-price or that the ranking score is the charge. For example, Google’s <a href="https://support.google.com/google-ads/answer/6297?hl=en">actual CPC documentation</a> describes additional thresholds and quality factors. The formulas here are simplified expected values for a teaching scenario, not a billing algorithm.</p>
<div class="formula">CPC bid (currency / click):
  expected currency / 1000 impressions = 1000 · P(click) · bid_CPC

CPA bid (currency / post-click conversion):
  expected currency / 1000 impressions
    = 1000 · P(click) · P(conversion | click) · bid_CPA</div>
<p>The CPA expression assumes the conversion is attributed through a click. View-through conversions or other objectives require a different model. The factor of 1,000 gives per-mille units. Multiplying a CPC bid by CVR would mix a conversion objective into a click-priced value without a stated economic reason.</p>
<div class="lab" id="ads-lab"><h3>Check the units</h3><label>Bid basis<select id="bid-basis" aria-label="Bid basis"><option value="cpc">Per click (CPC)</option><option value="cpa" selected>Per post-click conversion (CPA)</option></select></label><label>Click probability<input id="ctr" type="number" min="0" max="1" step="0.01" value="0.05"></label><label>Conversion probability given click<input id="cvr" type="number" min="0" max="1" step="0.01" value="0.10"></label><label>Bid (currency per billed event)<input id="bid" type="number" min="0" max="10000" step="1" value="20"></label><output id="ads-result" aria-live="polite"></output><p>These estimates exclude pricing rules, fees, budget optimization, and auction incentives.</p></div>
<h2 id="pipeline">2. Preserve eligibility through the scoring pipeline</h2>
<div class="pipeline" role="img" aria-label="Ads pipeline: eligibility, cheap scoring, calibrated predictions, allocation"><div><b>ELIGIBILITY</b>Policy + targeting + budget state<span>Current, auditable restrictions</span></div><div><b>SHORTLIST</b>Cheap score → bounded candidates<span>Measure lost value at cutoff</span></div><div><b>PREDICT</b>CTR / conversion estimates<span>Features + model + calibration version</span></div><div><b>ALLOCATE</b>Value + auction rules<span>Final checks and event logging</span></div></div>
<p>A cheap pre-scorer should preserve candidates likely to win under the expensive model, not simply maximize its own AUC. Evaluate shortlist recall against the final objective on replayable eligible sets. Sample expensive scores for dropped candidates to inspect the blind spot, with appropriate cost controls.</p>
<p>A logistic or tree baseline establishes feature and label quality. Neural models with learned categorical embeddings, crosses, or task-specific heads are candidates for later evaluation. The <a href="https://arxiv.org/abs/2008.13535">DCN-v2 paper</a> offers one interaction architecture; it does not imply that every ads workload needs it.</p>
<p>Protect final allocation from stale state. A cached prediction can be reused only with an explicit age and compatibility rule; budget and policy eligibility may need another check. If required state is unavailable, returning no ad can be safer for correctness than serving an ineligible “popular” fallback.</p>
<h2 id="labels">3. Conversion labels have both delay and selection</h2>
<p>Clicks arrive quickly; conversions may arrive after the training snapshot. Define an attribution event, deduplication key, time window, and revision policy. A recent impression with no recorded conversion is not the same as a mature negative.</p>
<p>A simple baseline trains on mature cohorts and accepts staleness. Alternatives model the observation delay or use corrections under explicit assumptions; they require evaluation across cohort age. <a href="https://wnzhang.net/share/rtb-papers/delayed-feedback.pdf">Chapelle’s delayed-feedback paper</a> formalizes this problem. A single universal waiting period is not justified across products.</p>
<p>Post-click CVR training also selects users who clicked. Combining CTR and CVR estimates requires attention to that selection and consistency between the heads. <a href="https://arxiv.org/abs/1804.07931">ESMM</a> is an example of modeling the impression → click → conversion sequence jointly. It is not a general cure for unmeasured confounding or every attribution issue.</p>
<h2 id="calibration">4. Calibrate to the serving population</h2>
<p>For a predicted probability near 0.1, inspect how often the event occurs in comparable held-out examples. Reliability diagrams, log loss, and business-relevant slices reveal different failures; aggregate calibration can hide a segment error. If negative sampling changes the training class balance, account for it before interpreting a raw model output as a serving probability.</p>
<p>Fit calibration on held-out, representative data, with mature labels for the conversion task. Sigmoid calibration has a constrained shape; isotonic is more flexible but can overfit with little data and introduce ties. Neither is categorically superior. <a href="https://scikit-learn.org/stable/modules/calibration.html">The scikit-learn guide</a> explains the trade-off. Version the calibrator with the model and monitor drift after launch.</p>
<p>Calibration matters because two candidates can have different bids. A probability distortion can change the ordering of probability × bid even when the probability-only ordering is preserved. Good calibration still does not prove the economic objective or auction mechanism is correct.</p>
<h2 id="evaluation">5. Evaluate value, user impact, and feedback</h2>
<p>Track shortlist survival, mature outcome prediction, calibration by cohort, latency, budget violations, and negative feedback. Revenue alone can improve while advertiser outcomes deteriorate; inspect conversions and advertiser-level concentration as well. Pacing and auction changes can create interference across impressions and campaigns, which should inform the experimental design.</p>
<p>Exploration needs a defined allocation policy, budget constraints, and logged selection probabilities. Do not substitute empirical click rate at a position for an examination propensity. For position-bias corrections, specify the observation model and validate the estimator; the <a href="https://arxiv.org/abs/1608.04468">counterfactual ranking literature</a> makes those assumptions explicit.</p>
<div class="exercise"><h3>Work the example</h3><p>Ad A has CTR 0.04, conditional CVR 0.10, and a CPA bid of 30. Ad B has CTR 0.06, conditional CVR 0.02, and a CPA bid of 50. Which has higher simplified expected value?</p><details><summary>Answer and the next question</summary><p>A: 1,000 × 0.04 × 0.10 × 30 = 120 per mille. B: 1,000 × 0.06 × 0.02 × 50 = 60. A wins under this simplified value model. Before serving it, verify current eligibility, probability calibration, the attribution definition, and the actual allocation mechanism.</p></details></div>
'''
CONTENT['search'] = '''
<p class="lead">A user searching for a listing has stated constraints. Personalization should help choose among valid answers; it should not quietly rewrite the trip.</p>
<h2 id="contract">1. Respect intent and availability</h2>
<p>Assume a marketplace query specifies destination, dates, party size, and optional price or amenity filters. The service returns ranked available listings. Use personalized history only under the product’s privacy rules, and preserve a useful signed-out experience.</p>
<p>Define which constraints are hard and which preferences are soft. A displayed price ceiling might include fees or only a base rate; get that contract right before ranking. Date availability and capacity are correctness constraints. A past preference for expensive listings is a soft signal that must not override a current explicit budget.</p>
<p>The objective could be a successful booking with low cancellation risk and low search effort. Clicks, wishlists, bookings, and completed stays represent different observation windows. Begin with a clear booking attribution rule and separate long-horizon quality guardrails rather than calling every click a successful match.</p>
<h2 id="pipeline">2. Retrieve valid candidates, then personalize</h2>
<div class="pipeline" role="img" aria-label="Marketplace pipeline: query constraints, multiple candidate sources, ranking, diverse valid results"><div><b>CONSTRAIN</b>Dates + geography + party size<span>Authoritative eligibility</span></div><div><b>RETRIEVE</b>Structured / lexical / vector pools<span>Coverage under those constraints</span></div><div><b>RANK</b>Query–listing fit + permitted user context<span>Session intent and long-term preferences</span></div><div><b>ASSEMBLE</b>Useful variety + final validity check<span>Price, host, and location distribution</span></div></div>
<p>Start with structured retrieval and a transparent relevance baseline. A learned personalized retrieval source is useful if it recovers valid candidates missed by the baseline. It cannot create availability. If approximate search is followed by hard filtering, too many retrieved results may disappear; overfetch, filtered indexing, or structured candidate sources are alternative responses. Measure recall on the eligible universe.</p>
<p>A ranker can begin with boosted trees over query–listing features: distance, total-price fit, capacity, and contextual quality. Pair-specific features often provide more value than naming a sophisticated architecture. Consider learned interactions when evidence supports them; <a href="https://arxiv.org/abs/2008.13535">DCN-v2</a> provides one concrete design.</p>
<h2 id="features">3. Let the session disagree with history</h2>
<p>Separate long-term preferences from current intent. A user who usually travels alone may be organizing a family trip. Feed the current query and permitted session state as explicit feature groups, and test cases where they contradict history.</p>
<div class="table-wrap" tabindex="0" role="region" aria-label="Feature freshness contracts"><table><thead><tr><th>Feature family</th><th>Example</th><th>Failure to guard against</th></tr></thead><tbody><tr><td>Listing state</td><td>Availability, current price, capacity</td><td>A stale prediction offering an invalid result</td></tr><tr><td>Historical preference</td><td>Typical budget or property type</td><td>History overpowering the explicit query</td></tr><tr><td>Session state</td><td>Recent filters and viewed regions</td><td>Late or cross-device actions polluting intent</td></tr><tr><td>Query–listing cross</td><td>Distance or total-price fit</td><td>Training features computed with future prices</td></tr></tbody></table></div>
<p>Log request-time feature versions or reconstructable snapshots. Store event-time and ingestion-time semantics for updates. If a listing price changed after the impression, training must use the old visible price. Merely sharing batch and streaming code does not guarantee identical data availability.</p>
<h2 id="learning">4. Train on observations without confusing them with preference</h2>
<p>A booking label is sparse and delayed. Define the unit—query, impression, or session—and deduplicate outcomes accordingly. Several impressions can precede one booking; treating each as an independent conversion can inflate the apparent sample size.</p>
<p>Pointwise prediction and pairwise ordering optimize different things. A within-query pairwise objective can sharpen relative ordering but does not automatically produce calibrated probabilities. If downstream components consume probabilities, evaluate calibration separately instead of assuming that adding a pointwise loss guarantees it.</p>
<p>Position affects observation. An inverse weight is meaningful only when its propensity matches the stated observation or logging model. Adding 1 / position-frequency to every binary label is not a generic unbiased recipe. Define examination assumptions, overlap, and weight clipping; examine variance and sensitivity. See <a href="https://arxiv.org/abs/1608.04468">Unbiased Learning-to-Rank with Biased Feedback</a> for a specific formal construction.</p>
<h2 id="coldstart">5. Cold start needs a route to exposure</h2>
<p>A new listing has content and structured attributes but little behavioral history. Give the model valid missing-history defaults, use attribute-based relevance, and ensure a candidate source can retrieve it. Exploration is pointless if retrieval always drops the new listing first.</p>
<p>For a new guest, query intent is already informative. A location-, date-, and price-aware baseline is more useful than global popularity. As the session develops, incorporate fresh signals without requiring a permanent user embedding. Maintain a privacy-compatible option for users who decline personalization.</p>
<p>Slate constraints can promote variety among valid results, but they can also reduce relevance. Specify a policy such as a host cap or a soft redundancy penalty, and evaluate the trade-off. Parity in booking rates alone is not proof of fairness: supply, exposure, relevance, and eligibility differ by segment.</p>
<h2 id="evaluation">6. Test the whole search journey</h2>
<p>Track eligible candidate coverage, ordering judgments, search abandonment, booking completion, cancellation, and result validity. Include cases with sparse inventory, restrictive dates, cold-start guests, and fresh listings. Compare performance at equal candidate and latency budgets.</p>
<p>For a teaching 200 ms target, reserve headroom and measure feature lookup, filtering, model inference, and pagination together. Use a current constraint-aware heuristic when personalization fails. A saved result page must not be treated as an availability guarantee at booking time.</p>
<div class="exercise"><h3>Inspect the hidden failure</h3><p>The ranker improves offline booking prediction, but restrictive-date queries return fewer useful results. What experiment would distinguish retrieval loss from ranking loss?</p><details><summary>Suggested answer</summary><p>Freeze a set of queries and an eligibility snapshot. Compare recall against a broader eligible reference set before scoring, then compare rankers on the same candidate set. Count candidates removed by date filters and source truncation. The ranker cannot recover candidates it never receives.</p></details></div>
'''

NAV = [(slug, label) for slug, label, _, _ in PAGES]
import re
for i, (slug, label, title, subtitle) in enumerate(PAGES):
    body = CONTENT[slug]
    headings = re.findall(r'<h2 id="([^"]+)">(.*?)</h2>', body)
    toc = ''.join(f'<a href="#{key}">{escape(re.sub("<.*?>", "", heading))}</a>' for key, heading in headings)
    nav = ''.join(f'<a href="{key}.html"'+(' aria-current="page"' if key == slug else '')+f'>{escape(text)}</a>' for key, text in NAV)
    prev = PAGES[i-1] if i else None
    nxt = PAGES[i+1] if i+1 < len(PAGES) else PAGES[0]
    prev_link = f'<a href="{prev[0]}.html">← {escape(prev[1])}</a>' if prev else '<span>Choose a case or read in order.</span>'
    out = f'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{escape(title) if slug == "index" else escape(title) + " — Designing Ranking Systems"}</title><meta name="description" content="{escape(subtitle)}"><link rel="stylesheet" href="style.css"><script src="labs.js" defer></script></head><body><a class="skip" href="#main">Skip to content</a><header class="top"><span>FIELD NOTES / RANKING SYSTEMS</span><span>Four case studies · October 2026</span></header><nav class="nav" aria-label="Chapters"><div class="nav-inner">{nav}</div></nav><div class="layout"><aside class="toc" aria-label="On this page"><strong>On this page</strong>{toc}</aside><main id="main"><div class="eyebrow">{escape(label)} / Systems study</div><h1>{escape(title)}</h1>{body}<nav class="next" aria-label="Continue reading">{prev_link}<a href="{nxt[0]}.html">{escape(nxt[1])} →</a></nav><footer>Original teaching notes · Scenario assumptions are illustrative · Updated October 9, 2026</footer></main></div></body></html>'''
    (ROOT / (slug + '.html')).write_text(out, encoding='utf-8')
    print(slug, len(re.sub('<[^>]+>', ' ', body).split()), 'words')
